fix: readNMRiumObject
cheminfo/nmr-load-save pull request #29
Opened 2022-10-21 03:20 UTC by jobo322

2022-10-21 15:34 UTC, lpatiny requested changes

2022-10-21 15:34 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
> +let cache: Record<string, any> = {};
We should never create a global variable. It should be inside the function.

2022-10-21 15:34 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
>    for (let datum of data.spectra) {
There is an interesting problem here because your code is executing the loading of the jcamp in parallel even if the URL is the same !

You could rather do something like
1. Find all the distinct jcampURL
2. Create the cache with this kind of untested code:

```js
const uniqueJcampURLs = [];
const promises = uniqueJcampURLs.map(jcampURL => fetch(jcampURL).then(response => response.text()).then(jcamp => parse(jcamp));
const parsedJcamps = await Promises.all(promises);

const cache = {};
for (let i=0; i<uniqueJcampURLs.length; i++) {
  cache[uniqueJcampURLs[i]]=parsedJcamps[i]
}
```
And then use the cache

2022-10-22 06:20 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
>    const data = migrate(nmriumData);
Please use something less generic for options type (and in general as name for typescript type). Maybe `ParsingOptions`.

Same if true for the type of return value of this method. `Output` is too generic.

2022-10-22 06:22 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
> +  const cache = getJcampPromisesFromURL(data, jcampParsingOptions);
The cache should not contain promises anymore. Please:
- rename `cache` to `sourceCache` (to plan when we will have other sources than jcampURL)
- implement a method `getSourceCache`

So this line becomes

`const sourceCache = getSourceCache`

2022-10-22 06:23 UTC, targos commented
Can you add unit tests?

2022-10-22 06:24 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
>  }
Add a funciton

```
async function getSourceCache() {
  const uniqueJcampURLs = [];
const promises = uniqueJcampURLs.map(jcampURL => fetch(jcampURL).then(response => response.text()).then(jcamp => parse(jcamp));
const parsedJcamps = await Promises.all(promises);
const cache = {};
for (let i=0; i<uniqueJcampURLs.length; i++) {
  cache[uniqueJcampURLs[i]]=parsedJcamps[i]
}
}
```

2022-10-22 06:25 UTC, lpatiny reviewed
I think it would be better to load and parse all the 'sources' (currently only jcampURL).

2022-10-22 06:59 UTC, lpatiny commented on src/reader/readNMRiumObject.ts
> +function appendData(
Please add jsDoc. I don't understand what are currentSpectra vs recent and what is the goal of the function.

2022-10-25 04:23 UTC, merged

2022-10-25 04:54 UTC, targos commented
This is a big change. It's a bit sad that you merged it without a final review 😕